### ISSUE TITLE
随机的淫乱度不足

### ISSUE THREAD

**Issue by XHLin-gamer** [RimoChan/yinglish#4]
随机地添加省略号似乎淫乱度不足，能不能考虑根据汉语单词词性的不同或者建立一个关键词的词典来添加淫乱符号

**Comment by XHLin-gamer** [comment]
随机地添加省略号似乎淫乱度不足，能不能考虑根据汉语单词词性的不同或者建立一个关键词的词典来添加淫乱符号
……随机……地……添加省……省略号似……似乎……淫乱……度……不足…………能不……不能考……考虑……根据汉……汉语……〇〇词……词性……的……不同或……或者……建立一……一个关……关键词……的词……词典……来……添加淫……淫乱……符号

**Comment by RimoChan** [comment]
不是，省略号是因为说到一半的时候被啪得很用力，这个和文本内容是没有关系的啊……

**Comment by XHLin-gamer** [comment]
原来如此，我理解了。
