### ISSUE TITLE
考虑过出一个二次元尴尬话分支吗

### ISSUE THREAD

**Issue by sinsiuwo** [RimoChan/yinglish#6]
比如随机插入以下列表中内容
['呐呐呐','米娜桑','desu','(∗❛ั❛❛ั∀❛ั❛ั❛ั∗)✧*','desu呦呐','哎豆哎豆','喵(=^▽^=)','呦~','米❤娜','キ-ト','(*^ω^*)']

**Comment by RimoChan** [comment]
没事，你看代码就几行，你可以自己做1个！
